### ISSUE TITLE
`ppv-lite86` fails to compile when zerocopys `derive` feature is active

### ISSUE THREAD

**Issue by Abestanis** [cryptocorrosion/cryptocorrosion#77]
The yanked version `0.2.19` of `ppv-lite86` fails to compile when the `derive` feature of `zerocopy` is active. The feature is not enabled by `ppv-lite86`, but can be transitively enabled by any other crate in the build tree.

Try to compile the following minimal project:

<details><summary>Minimal project</summary>

`Cargo.toml`
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
ppv-lite86 = { version = "=0.2.19", features = ["no_simd"] }
zerocopy = { version = "0.7", features = ["derive"] }
```
--------

`src/lib.rs`
```rust
use ppv_lite86 as _;
use zerocopy as _;
```
</details>

**Stacktrace**
```
   Compiling ppv-lite86 v0.2.19
error[E0252]: the name `AsBytes` is defined multiple times
 --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ppv-lite86-0.2.19/src/generic.rs:7:23
  |
6 | use zerocopy::{AsBytes, FromBytes};
  |                ------- previous import of the macro `AsBytes` here
7 | use zerocopy_derive::{AsBytes, FromBytes, FromZeroes};
  |                       ^^^^^^^--
  |                       |
  |                       `AsBytes` reimported here
  |                       help: remove unnecessary import
  |
  = note: `AsBytes` must be defined only once in the macro namespace of this module

error[E0252]: the name `FromBytes` is defined multiple times
 --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ppv-lite86-0.2.19/src/generic.rs:7:32
  |
6 | use zerocopy::{AsBytes, FromBytes};
  |                         --------- previous import of the macro `FromBytes` here
7 | use zerocopy_derive::{AsBytes, FromBytes, FromZeroes};
  |                                ^^^^^^^^^--
  |                                |
  |                                `FromBytes` reimported here
  |                                help: remove unnecessary import
  |
  = note: `FromBytes` must be defined only once in the macro namespace of this module

For more information about this error, try `rustc --explain E0252`.
error: could not compile `ppv-lite86` (lib) due to 2 previous errors
```

This problem was introduced by ee6c7d4056780ee58593597b739bb501be567e03. [`probe-rs` had a similar issue](https://github.com/probe-rs/probe-rs/issues/2613).

I am willing to provide a pull request, but there is two possible solutions to the problems. Which one do you prefer?

* Remove the dependency on `zerocopy_derive` and enable `zerocopy`s  `derive` feature. This is the solution that was adopted by [`probe-rs`](https://github.com/probe-rs/probe-rs/pull/2614).
* Use the traits under a different name:
  ```diff
  - use zerocopy::{AsBytes, FromBytes};
  + use zerocopy::{AsBytes as _, FromBytes as _}; 
  ```

**Comment by kazcw** [comment]
I'd be happy to receive a PR!

> * Remove the dependency on `zerocopy_derive` and enable `zerocopy`s  `derive` feature. This is the solution that was adopted by [`probe-rs`](https://github.com/probe-rs/probe-rs/pull/2614).

We could do this for now. I prefer to take on a little extra complexity to provide a small build-time benefit to a *large* number of builds, but it will need full CI testing with the `derive` feature of `zerocopy` enabled, covering all platform-specific code in all crates using `zerocopy_derive`; that's probably easier for me to implement (for a future release when I have time) since github doesn't run modified workflows in a PR unless it is from a repo owner.
